version: '3.8'
services:

  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  bot:
    restart: always
    image: astalavista91/leaderbot:latest
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py main"
    depends_on:
      - db
    env_file:
      - ./.env
  admin:
    restart: always
    image: astalavista91/leaderbot:latest
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    depends_on:
      - bot
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


    depends_on:
      - web

