# Generated by Django 2.2.16 on 2024-05-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240512_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('Admin', 'Админ'), ('User', 'Пользователь')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
