# Generated by Django 2.2.16 on 2024-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('Admin', 'Админ'), ('User', 'Пользователь')], max_length=10, verbose_name='Количество сообщений'),
        ),
    ]
